### ISSUE TITLE
Install procedure doesn't really work with GNAT Pro

### ISSUE THREAD

**Issue by ptroja** [AdaCore/gnat-gdb-scripts#4]
The Install procedure for `.gdbinit` suggests to put there:
```sys.path.append('/home/ptroja/gnat-gdb-scripts/gnatdbg')```
but I only got your fix for #3 to work after changing that line to:
```sys.path.insert(0, '/home/ptroja/gnat-gdb-scripts')```

Apparently _gnat-gdb-scripts_ are already shipped with GNAT (Pro?), at least they already came with my recent GNAT from GAIA. Appending to the `sys.path` didn't work, because gdb was still picking the package that came with GNAT, not the one that I took from Github; that's why I had to "prepend" to `sys.path` with `insert`.

Also, for `python import gnatdbg` to work, the `sys.path` must include the directory where `gnatdbg` is located, not the `gnatdbg` directory itself.

Otherwise, your fix works great, thanks!

**Comment by pmderodat** [comment]
Hello @ptroja,

Prepending is aood idea, we’ll do that: thank you for the suggestion!

> Also, for python import gnatdbg to work, the sys.path must include the directory where gnatdbg is located, not the gnatdbg directory itself.

I think the current phrasing describes exactly that: do you think it should be improved? I’ll try to add a note.
